const te=new TextEncoder(),b64=a=>btoa(String.fromCharCode(...a)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const rnd=()=>b64(crypto.getRandomValues(new Uint8Array(32))), hex=a=>[...new Uint8Array(a)].map(x=>x.toString(16).padStart(2,'0')).join('');
const sha=async x=>hex(await crypto.subtle.digest('SHA-256',te.encode(x)));
async function pwd(p,s){let k=await crypto.subtle.importKey('raw',te.encode(p),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:te.encode(s),iterations:310000},k,256))}
const response=(v,status=200,headers={})=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers}});
const bad=(s,status=400)=>response({error:s},status), cookie=(v,age)=>`trace_session=${v}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${age}`;
const future=ms=>new Date(Date.now()+ms).toISOString(), valid=s=>typeof s==='string'&&/^[A-Za-z0-9_-]{3,40}$/.test(s);
async function createSession(db,id){const token=rnd();await db.prepare('INSERT INTO sessions(id_hash,user_id,expires_at) VALUES(?,?,?)').bind(await sha(token),id,future(604800000)).run();return token}
export async function onRequest({request,env,params}){const db=env.DB;if(!db)return bad('D1 binding DB is missing',503);const action=(params.path||[]).join('/'),method=request.method,origin=new URL(request.url).origin;if(method==='POST'&&request.headers.get('Origin')&&request.headers.get('Origin')!==origin)return bad('Invalid origin',403);
try{
if(action==='me'&&method==='GET'){const token=request.headers.get('Cookie')?.match(/(?:^|;\s*)trace_session=([^;]+)/)?.[1];if(!token)return response({user:null});const user=await db.prepare('SELECT u.id,u.company_id,u.username,u.email,c.trial_ends_at FROM sessions s JOIN users u ON s.user_id=u.id JOIN companies c ON c.id=u.company_id WHERE s.id_hash=? AND s.expires_at>? AND c.trial_ends_at>?').bind(await sha(token),new Date().toISOString(),new Date().toISOString()).first();return response({user:user||null})}
if(action==='logout'&&method==='POST'){const token=request.headers.get('Cookie')?.match(/(?:^|;\s*)trace_session=([^;]+)/)?.[1];if(token)await db.prepare('DELETE FROM sessions WHERE id_hash=?').bind(await sha(token)).run();return response({ok:true},200,{'Set-Cookie':cookie('',0)})}
if(method!=='POST')return bad('Not found',404);let b;try{b=await request.json()}catch{return bad('Invalid JSON')}
if(action==='trial'){const company_id=String(b.company_id||'').toUpperCase(),username=String(b.username||''),email=String(b.email||'').trim().toLowerCase(),password=b.password;if(!valid(company_id)||!valid(username)||!/^\S+@\S+\.\S+$/.test(email)||typeof password!=='string'||password.length<12||password.length>256)return bad('Valid company ID, username, email and password (12+ characters) required');if(await db.prepare('SELECT id FROM companies WHERE id=?').bind(company_id).first())return bad('Company ID already exists',409);const id=crypto.randomUUID(),salt=rnd(),hash=await pwd(password,salt),trial_ends_at=future(14*86400000);await db.batch([db.prepare('INSERT INTO companies(id,name,trial_ends_at) VALUES(?,?,?)').bind(company_id,company_id,trial_ends_at),db.prepare('INSERT INTO users(id,company_id,username,email,password_salt,password_hash) VALUES(?,?,?,?,?,?)').bind(id,company_id,username,email,salt,hash)]);const token=await createSession(db,id);return response({user:{id,company_id,username,email,trial_ends_at}},201,{'Set-Cookie':cookie(token,604800)})}
if(action==='login'){const company_id=String(b.company_id||'').toUpperCase(),username=String(b.username||'');if(!valid(company_id)||!valid(username)||typeof b.password!=='string')return bad('Invalid credentials',401);const u=await db.prepare('SELECT u.*,c.trial_ends_at FROM users u JOIN companies c ON c.id=u.company_id WHERE u.company_id=? AND u.username=?').bind(company_id,username).first();if(!u||await pwd(b.password,u.password_salt)!==u.password_hash)return bad('Invalid credentials',401);if(u.trial_ends_at<new Date().toISOString())return bad('Trial expired. Contact support.',403);const token=await createSession(db,u.id);return response({user:{id:u.id,company_id:u.company_id,username:u.username,email:u.email,trial_ends_at:u.trial_ends_at}},200,{'Set-Cookie':cookie(token,604800)})}
if(action==='forgot'){const company_id=String(b.company_id||'').toUpperCase(),email=String(b.email||'').trim().toLowerCase();const u=await db.prepare('SELECT id,email FROM users WHERE company_id=? AND email=?').bind(company_id,email).first();if(u&&env.RESEND_API_KEY&&env.RESET_FROM_EMAIL){const token=rnd();await db.prepare('INSERT INTO password_resets(token_hash,user_id,expires_at) VALUES(?,?,?)').bind(await sha(token),u.id,future(1800000)).run();await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.RESET_FROM_EMAIL,to:[email],subject:'Reset your TRACE password',text:`Use this link within 30 minutes: ${origin}/?reset=${encodeURIComponent(token)}`})})}return response({ok:true})}
if(action==='reset'){if(typeof b.token!=='string'||b.token.length<30||typeof b.password!=='string'||b.password.length<12||b.password.length>256)return bad('Invalid reset request');const hash=await sha(b.token),row=await db.prepare('SELECT user_id FROM password_resets WHERE token_hash=? AND used_at IS NULL AND expires_at>?').bind(hash,new Date().toISOString()).first();if(!row)return bad('Reset link expired or invalid');const salt=rnd(),pw=await pwd(b.password,salt);await db.batch([db.prepare('UPDATE users SET password_salt=?,password_hash=? WHERE id=?').bind(salt,pw,row.user_id),db.prepare('UPDATE password_resets SET used_at=? WHERE token_hash=?').bind(new Date().toISOString(),hash),db.prepare('DELETE FROM sessions WHERE user_id=?').bind(row.user_id)]);return response({ok:true})}
return bad('Not found',404)
}catch(e){console.error('auth request failed',e);return bad('Server error',500)}
}
